I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script
    "Сонце в зеніті і ти пришвидшуєш крок, ховаючись від нього під просторою парасолею."
OSError: Couldn't find file 'a-jazz-piano-110481.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script
    "Сонце в зеніті і ти пришвидшуєш крок, ховаючись від нього під просторою парасолею."
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\character.py", line 1045, in do_display
    display_say(who,
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\display\core.py", line 2734, in interact_core
    renpy.audio.audio.interact()
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1251, in interact
    periodic()
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1205, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1183, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1125, in periodic_pass
    c.periodic()
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'a-jazz-piano-110481.mp3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Zdybanka 1.0
Wed Jul  3 22:32:23 2024
